// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx7fJjX5DzfInL-4MFzl1DXiGBJcOJAA4',
    appId: '1:185218377889:web:c0b683231a9855d424a8e0',
    messagingSenderId: '185218377889',
    projectId: 'deep-learnin-9128c',
    authDomain: 'deep-learnin-9128c.firebaseapp.com',
    storageBucket: 'deep-learnin-9128c.appspot.com',
    measurementId: 'G-JHR6KX0M4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUozvSwbQWD_W2IZOpgzx9LgESt0N3ogU',
    appId: '1:185218377889:android:4d6058d6d89887ff24a8e0',
    messagingSenderId: '185218377889',
    projectId: 'deep-learnin-9128c',
    storageBucket: 'deep-learnin-9128c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9idfO7VawdM7DUzrjGrfNAHh4RL3gTgE',
    appId: '1:185218377889:ios:b0b61a7ffa09e9e224a8e0',
    messagingSenderId: '185218377889',
    projectId: 'deep-learnin-9128c',
    storageBucket: 'deep-learnin-9128c.appspot.com',
    iosClientId: '185218377889-pkikbos697etu4o4teucorgalinekcnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverStateDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9idfO7VawdM7DUzrjGrfNAHh4RL3gTgE',
    appId: '1:185218377889:ios:b0b61a7ffa09e9e224a8e0',
    messagingSenderId: '185218377889',
    projectId: 'deep-learnin-9128c',
    storageBucket: 'deep-learnin-9128c.appspot.com',
    iosClientId: '185218377889-pkikbos697etu4o4teucorgalinekcnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverStateDetection',
  );
}
